<?php

namespace CFDev\Tests\Unit\Support;

use CFDev\Support\NameResolver;
use CFDev\Tests\Unit\CFDevTestCase;
use Brain\Monkey\Functions;

class NameResolverTest extends CFDevTestCase
{
    protected function setUp(): void
    {
        parent::setUp();
        // Simulate WordPress sanitize_title: lowercase + spaces to hyphens
        Functions\when('sanitize_title')->alias(fn(string $s) => strtolower(str_replace(' ', '-', $s)));
    }

    // -------------------------------------------------------------------------
    // String input — auto-pluralization
    // -------------------------------------------------------------------------

    public function testStringInputSlugIsUglified(): void
    {
        $this->assertSame('book', (new NameResolver('book'))->slug);
    }

    public function testStringInputSingularIsBeautified(): void
    {
        $this->assertSame('Book', (new NameResolver('book'))->singular);
    }

    public function testStringInputPluralIsAutoGenerated(): void
    {
        // beautify('book') = 'Book', pluralize('Book') = 'Books'
        $this->assertSame('Books', (new NameResolver('book'))->plural);
    }

    public function testStringInputWithUnderscoreSlugUsesHyphenThenUnderscore(): void
    {
        // sanitize_title converts spaces to hyphens, uglify converts hyphens to underscores
        $this->assertSame('my_post', (new NameResolver('my post'))->slug);
    }

    public function testStringInputSingularCapitalizesWords(): void
    {
        $this->assertSame('My Post', (new NameResolver('my_post'))->singular);
    }

    // -------------------------------------------------------------------------
    // Array input [singular, plural] — explicit plural
    // -------------------------------------------------------------------------

    public function testArrayInputSlugComesFromFirstElement(): void
    {
        $this->assertSame('book', (new NameResolver(['book', 'books']))->slug);
    }

    public function testArrayInputSingularComesFromFirstElement(): void
    {
        $this->assertSame('Book', (new NameResolver(['book', 'books']))->singular);
    }

    public function testArrayInputPluralComesFromSecondElement(): void
    {
        $this->assertSame('My Books', (new NameResolver(['book', 'my books']))->plural);
    }

    public function testArrayInputExplicitPluralOverridesAutoPluralize(): void
    {
        // 'person' auto-pluralizes to 'people', but we provide 'members'
        $this->assertSame('Members', (new NameResolver(['person', 'members']))->plural);
    }

    // -------------------------------------------------------------------------
    // Readonly enforcement
    // -------------------------------------------------------------------------

    public function testSlugIsReadonly(): void
    {
        $name = new NameResolver('book');
        $this->expectException(\Error::class);
        $name->slug = 'hacked'; // @phpstan-ignore-line
    }

    public function testSingularIsReadonly(): void
    {
        $name = new NameResolver('book');
        $this->expectException(\Error::class);
        $name->singular = 'hacked'; // @phpstan-ignore-line
    }
}
